// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwCMdcv6djIJe6tvIoksRdKnx-wLFMZc4',
    appId: '1:321339512121:web:456b30134e0f76a80f04e8',
    messagingSenderId: '321339512121',
    projectId: 'mobile1-3bc4c',
    authDomain: 'mobile1-3bc4c.firebaseapp.com',
    storageBucket: 'mobile1-3bc4c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvTBFJ19j7qqy2oPVS1y1mPhmdmLFxOks',
    appId: '1:321339512121:android:b4c0659adf05d3270f04e8',
    messagingSenderId: '321339512121',
    projectId: 'mobile1-3bc4c',
    storageBucket: 'mobile1-3bc4c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb3DsB4rDtmnrHvpCsIwRAzgv88Uz_bno',
    appId: '1:321339512121:ios:de324a92a4dbdf710f04e8',
    messagingSenderId: '321339512121',
    projectId: 'mobile1-3bc4c',
    storageBucket: 'mobile1-3bc4c.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDb3DsB4rDtmnrHvpCsIwRAzgv88Uz_bno',
    appId: '1:321339512121:ios:de324a92a4dbdf710f04e8',
    messagingSenderId: '321339512121',
    projectId: 'mobile1-3bc4c',
    storageBucket: 'mobile1-3bc4c.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwCMdcv6djIJe6tvIoksRdKnx-wLFMZc4',
    appId: '1:321339512121:web:d6fa0a4815919fe20f04e8',
    messagingSenderId: '321339512121',
    projectId: 'mobile1-3bc4c',
    authDomain: 'mobile1-3bc4c.firebaseapp.com',
    storageBucket: 'mobile1-3bc4c.appspot.com',
  );

}